management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: '5'
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: grading
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: grading-service
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    password: '3amirform' #change password and put your own
    driver-class-name: org.postgresql.Driver
    username: postgres #channge username and put your own
    url: jdbc:postgresql://localhost:5440/fyp_grading_db #change this url to where you are running postgres locally with the fyp_grading_db already created and the student and professor schemas added to schemas
server:
  port: 8080
